c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/dashy
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/matchmaker
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/2op
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/3lywa
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/4728-b
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/4-q
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/alenazi
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/alright-accord
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/andrew-shaw-care
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/appcreators
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/app-face
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/apps4canadians
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/to-be-defined
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/cq-labs
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/ase
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/async
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/atermoiement
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/avatar
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/a-whovian
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/batfolk
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/bentranter
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/big-data
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/bigwoah
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/big-yellow-cat
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/biohazard
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/test
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/bi-xenon
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/blathering-blatherskite
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/blue-monkey
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/blue-socks
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/bowzer
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/brad-ryan
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/brain-drain
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/brazil
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/brogrammers
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/brown-sabbath
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/cada
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/cadorette
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/calgary-developers
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/proitdev
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/capaciouslabs
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/carribeanada
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/cfg
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/feneris
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/city-reality
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/code-catalyst
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/accenture-code-masters
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/codex
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/codingforce
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/collatz
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/cool-beans
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/crazycanucks
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/crimson
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/crowdq
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/cryptr
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/cupric
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/cychess
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/dancing-lion
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/dashy
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/data-exp
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/data-explorers
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/dataio
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/datapower
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/datarebel
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/data-z
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/da-vinci-coders
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/daydream-library
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/d-code
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/deedeekaka
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/demofirst
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/digital-doctors
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/dlgr-team
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/double-double
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/drost-team
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/ed-209
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/eencompass
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/eij
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/einstein
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/electricsheep
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/eli-marshal
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/emergence
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/datum
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/evgeny-vinnik
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/eyereturn-marketing
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/ezmoney-ezlife
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/fatalexception
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/fettuccine-cholotta-designs
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/fidchell-tech
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/fof
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/for-a-better-future
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/forbidden-city
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/friend-boat
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/fundy-code
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/fuzzybit
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/generation-next
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/geogeeks
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/geothink
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/getmapped
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/good-you
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/hackabyte
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/hack-lightly
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/healthhive
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/health-masters
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/hectanooga
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/hopefully-this-goes-over-well
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/hot-dog
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/i2p
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/i7zi
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/icarly-fan-club
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/illuminati
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/illuminati-2
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/i-need-money
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/insyncminds
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/insyncminds-2
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/interactive-design-labs
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/interchange2014
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/ippetad
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/iuservice
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/jac-php
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/jac-team-4
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/jagb-technologies
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/jai
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/jaks
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/jam-slam
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/jeremy-tregunna
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/joeflix
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/john-abbott-college-computer-science-devclub
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/jollyfish
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/jonah
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/justice-initiative
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/justin-fox
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/kindness-connect
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/kite
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/kris
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/todo
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/legions
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/len-payne
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/letter-r
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/liberty-village
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/life-net
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/life-net-ca
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/livequake
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/lounge-group
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/manatee-digital
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/mark-jenkins-w-python
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/mcgill-tbd
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/me
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/meet
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/meet-2
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/memyselfandi
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/mg
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/mintah
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/moyers-stark
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/na
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/namak
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/nathan-boyd
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/navigator_
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/neverland
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/ninja-cornz
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/nobis-studios
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/astroids
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/nullpointer
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/numbermuncher
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/old-lady-perfume-with-menthol-filling
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/opc
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/open-data
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/open-data-for-canada
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/open-source
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/operation-n
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/orchard-labs
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/ozco
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/paiva
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/path2go
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/pirocso
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/power-team-5
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/michael
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/puglyfe
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/qq
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/quadriga
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/quokka
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/rdff
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/renegade-digital-media-inc
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/googa
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/sacred-chicken
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/sample-team
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/sceua-sou-a
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/schrodinger-s-team
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/scout-mop-projects-research
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/semantic-team-canada
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/sentrl
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/sfu-jammers-simon-fraser-university
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/open_data_browser
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/singleton
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/sizzleton
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/sloan
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/smarterdata
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/smartypants
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/smu-maple-friends
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/smunav
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/smu-team-delta
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/springbook
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/ssh
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/struct-by_lightning
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/st-theresa-titans
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/such-team
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/sudoers
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/super-cute-kittens
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/supernaut
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/supersymmetry
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/sylm
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/synaptic-sugar
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/t5g
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/tag-team
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/tarotech
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/smu-team
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/team-63
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/team-ase
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/team-awesome
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/teamblue
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/team-blue
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/team-cool
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/team-datadrop
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/team-extreme
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/team-name
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/pony
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/team-quantified
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/team-team
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/teamtigley
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/team-transparency
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/temp_team
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/tentacular-apps
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/ten-to-the-hundred
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/teree
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/the-burly-mountaineers
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/the-carrot-crew
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/the-concordia-null-pointers
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/the-corollary
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/the-david-chang-experience
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/the-graduates
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/the-hive
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/the-human-beings
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/the-iterators
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/the-jalapeno
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/the-pattern-finder
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/thermostat
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/the-siren-and-the-beeps
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/those-dewolfes-creative
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/thunder-bay-infometrics
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/titanium
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/top-chef
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/toronto-team
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/totally-not-virgins
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/trak
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/trevordev
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/triangle
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/tt
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/turn-me-on
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/srsports
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/twoggle
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/uberpro
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/undefined
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/unicorn
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/united
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/unlimited-famous
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/untitled
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/valknut
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/votapp
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/wartortle
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/wasted-potential
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/waterloo
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/wav
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/ycdumpling
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/west-coast-express
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/winnipeg-c-o-d-e
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/xtatic
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/zejp
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/zeus
c:\perl\bin\perl jons.pl https://canadianopendataexperience.com/teams/zola
