application: tempdebug

version: opendata2
runtime: python27
api_version: 1
threadsafe: yes  

default_expiration: '365d'

builtins:
- appstats: off

inbound_services:
- warmup
- mail
- channel_presence

libraries:
- name: django
  version: latest
  
- name: lxml   
  version: latest
- name: PIL
  version: latest
- name: numpy
  version: latest
- name: pycrypto
  version: latest 
  
handlers:

- url: /_ah/remote_api 
  script: google.appengine.ext.remote_api.handler.application 
  login: admin 
  
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /jqtouch
  static_dir: static/jqtouch/
  
- url: /fantasm.*
  script: fantasm.main
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /css
  static_dir: static/css/

- url: /images
  static_dir: static/images/
  
- url: /img
  static_dir: static/images/
  
- url: /js
  static_dir: static/js/
  
- url: /static
  static_dir: static/

- url: /media/admin
  static_dir: django/contrib/admin/media/

- url: /media
  static_dir: _generated_media/
  expiration: '365d' 
  
- url: /raw
  static_dir: static/raw/
  application_readable: true
  
- url: /devcon/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: djangoappengine.main.application
- url: /cache.manifest
  static_files: cache.manifest
  mime_type: text/cache-manifest
  upload: cache.manifest