application: cguardianmarketing
version: 3
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

handlers:
- url: /static
  static_dir: static
  
- url: /css
  static_dir: static/css/

- url: /images
  static_dir: static/images/
  
- url: /img
  static_dir: static/images/
  
- url: /js
  static_dir: static/js/
  
- url: /fashion
  static_dir: static/fashion/

- url: /favicon.ico
  static_files: static/assets/img/icons/favicon.ico
  upload: static/assets/img/icons/favicon.ico

- url: /apple-touch-icon-precomposed.png
  static_files: static/assets/img/icons/apple-touch-icon-57x57-precomposed.png
  upload: static/assets/img/icons/apple-touch-icon-57x57-precomposed.png

- url: /apple-touch-icon-144x144-precomposed.png
  static_files: static/assets/img/icons/apple-touch-icon-144x144-precomposed.png
  upload: static/assets/img/icons/apple-touch-icon-144x144-precomposed.png

- url: /apple-touch-icon-114x114-precomposed.png
  static_files: static/assets/img/icons/apple-touch-icon-114x114-precomposed.png
  upload: static/assets/img/icons/apple-touch-icon-114x114-precomposed.png

- url: /apple-touch-icon-72x72-precomposed.png
  static_files: static/assets/img/icons/apple-touch-icon-72x72-precomposed.png
  upload: static/assets/img/icons/apple-touch-icon-72x72-precomposed.png

- url: /apple-touch-icon-57x57-precomposed.png
  static_files: static/assets/img/icons/apple-touch-icon-57x57-precomposed.png
  upload: static/assets/img/icons/apple-touch-icon-57x57-precomposed.png

- url: /apple-touch-icon.png
  static_files: static/assets/img/icons/apple-touch-icon-57x57-precomposed.png
  upload: static/assets/img/icons/apple-touch-icon-57x57-precomposed.png

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /humans.txt
  static_files: humans.txt
  upload: humans.txt

- url: /.*
  script: main.application
  

inbound_services:
- mail


libraries:
  - name: django
    version: 1.4
